#app/config/routing.yml
# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal




TiendaBundle:
    resource: "@TiendaBundle/Resources/config/routing.yml"
    prefix:   /

CiudadBundle:
    resource: "@CiudadBundle/Resources/config/routing.yml"
    prefix:   /

OfertaBundle:
    resource: "@OfertaBundle/Resources/config/routing.yml"
    prefix:   /

pagina_estatica:
    pattern:  /sitio/{pagina}/
    defaults: { _controller: OfertaBundle:Sitio:estatica }

UsuarioBundle:
    resource: "@UsuarioBundle/Resources/config/routing.yml"
    prefix:   /usuario


