#app/config/routing.yml
# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal

CiudadBundle:
    resource: "@CiudadBundle/Resources/config/routing.yml"
    prefix:   /{_locale}
    requirements:
        _locale: en|es
    defaults:
        _locale: es

OfertaBundle:
    resource: "@OfertaBundle/Resources/config/routing.yml"
    prefix:   /{_locale}
    requirements:
        _locale: en|es
    defaults:
        _locale: es

TiendaBundle:
    resource: "@TiendaBundle/Resources/config/routing.yml"
    prefix:   /{_locale}
    requirements:
        _locale: en|es
    defaults:
        _locale: es
        
Extranet:
    resource: "@TiendaBundle/Resources/config/extranet/routing.yml"
    prefix:   /extranet

UsuarioBundle:
    resource: "@UsuarioBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/usuario
    requirements:
        _locale: en|es
    defaults:
        _locale: es

pagina_estatica:
    pattern:  /{_locale}/sitio/{pagina}/
    defaults: { _controller: OfertaBundle:Sitio:estatica, _locale: es }
    requirements:
        _locale: en|es
# Ruta completa de la portada (con el slug de la ciudad)
portada:
    pattern: /{_locale}/{ciudad}
    defaults: { _controller: OfertaBundle:Default:portada, ciudad: malaga, _locale: es }
# Ruta simple de la portada
_portada:
    pattern: /
    defaults: { _controller: OfertaBundle:Default:portada, ciudad: malaga, _locale: es }


