security:
    firewalls:
        frontend:
            pattern:     ^/
            anonymous:   ~
            form_login:
                login_path: /usuario/login
                check_path: /usuario/login_check
    access_control:
        - { path: ^/usuario/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/usuario/registro, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/usuario/*, roles: ROLE_USUARIO }
    providers:
        usuarios:
            entity: { class: Cupon\UsuarioBundle\Entity\Usuario, property: email }
    encoders:
        Cupon\UsuarioBundle\Entity\Usuario: plaintext
        #Symfony\Component\Security\Core\User\UserInterface: plaintext
        #Cupon\UsuarioBundle\Entity\Usuario: { algorithm: sha512, iterations: 10 }