## app/config/services.yml
services:
    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }
    twig.extension.debug:
        class: Twig_Extensions_Extension_Debug
        tags:
            - { name: twig.extension }
    twig.extension.cupon:
        class: Cupon\OfertaBundle\Twig\Extension\CuponExtension
        tags:
            - { name: twig.extension }
    cupon.ofertabundle.listener.request:
        class: Cupon\OfertaBundle\Listener\RequestListener
        tags:
            - { name: kernel.event_listener, event: kernel.request }
