# Ruta completa de la portada (con el slug de la ciudad)
portada:
    pattern: /{ciudad}
    defaults: { _controller: OfertaBundle:Default:portada }
# Ruta simple de la portada
_portada:
    pattern: /
    defaults: { _controller: OfertaBundle:Default:portada }