parameters:
#    usuario.example.class: Cupon\UsuarioBundle\Example

services:
#    usuario.example:
#        class: %usuario.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    login_listener:
        class: Cupon\UsuarioBundle\Listener\LoginListener
        arguments: [@security.context, @router]
        tags:
            - { name: kernel.event_listener, event: security.interactive_login }
            - { name: kernel.event_listener, event: kernel.response }